# Generated by Django 3.2 on 2023-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('work_anniversary', 'Work Anniversary')], max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birt_hday', 'Birthday'), ('work_anniversary', 'Work Anniversary')], max_length=20)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
